import React from "react";
import {Button,Card,Eyebrow,Icon,RiskBadge} from "../components/common/UI";
export default function Reports({result,history,readings}){
 const exportJson=()=>{const blob=new Blob([JSON.stringify({generated_at:new Date().toISOString(),result,history,readings},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`CRAI_report_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 return <main className="content"><div className="page-head"><div><Eyebrow>REPORTS · DECISION TRACEABILITY</Eyebrow><h1>Field report</h1><p>Export the current CRAI assessment with its evidence chain and deterministic decision context.</p></div><div className="page-actions"><Button variant="secondary" onClick={()=>window.print()}><Icon name="report"/> Print report</Button><Button onClick={exportJson}><Icon name="download"/> Export JSON</Button></div></div>
 <div className="report-grid"><Card className="report-summary"><Eyebrow>CURRENT ASSESSMENT</Eyebrow>{result?<><div className="report-risk"><RiskBadge level={result.risk.level}/><strong>{Number(result.risk.score).toFixed(1)}</strong><span>/100</span></div><h2>{result.decision.action}</h2><p>{result.decision.rationale||"Deterministic CRAI decision."}</p><div className="report-fields"><div><small>Zone</small><b>{result.context?.zone_id||"A1"}</b></div><div><small>Condition</small><b>{result.visual?.disease||"Unknown"}</b></div><div><small>Visual confidence</small><b>{Number(result.visual?.confidence||0).toFixed(1)}%</b></div><div><small>Evidence sources</small><b>{result.evidence?.evidence_count??"Derived"}</b></div></div></>:<div className="empty-inline">No completed assessment. Start an observation.</div>}</Card><Card><Eyebrow>TRACEABILITY</Eyebrow><h2>CRAI evidence chain</h2><div className="report-pipeline">{["Image quality","Disease AI","Evidence evaluation","Adaptive evidence","Fusion V1.5","Deterministic decision","Judge explanation"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><small>{i===6?"Explanation only":"Executed"}</small></div>)}</div></Card></div>
 <Card><div className="card-title-row"><div><Eyebrow>REPORT PRINCIPLES</Eyebrow><h2>What this report guarantees</h2></div></div><div className="report-principles"><div><Icon name="shield"/><b>Risk is deterministic</b><span>CRAI Fusion V1.5 remains the source of truth for field risk.</span></div><div><Icon name="chip"/><b>Evidence is traceable</b><span>Source and freshness are kept visible rather than hidden behind a single score.</span></div><div><Icon name="leaf"/><b>LLM is explanation-only</b><span>Local advisory output can explain the decision but cannot overwrite it.</span></div></div></Card>
 </main>
}
