import React from "react";
import {Button,Card,Eyebrow,Icon,StatusDot} from "../components/common/UI";
import {ageMinutes,fmtTime,freshness} from "../utils/crai";
export default function Sensors({readings,online,backend,acquire,simulate,state,error,zoneId="A1"}){
 const targetZone=String(zoneId||"A1").toUpperCase();
 const inZone=readings.filter(r=>String(r?.zone_id||"").toUpperCase()===targetZone);
 const sorted=[...inZone].sort((a,b)=>ageMinutes(a.timestamp)-ageMinutes(b.timestamp));
 // Hardware-first display: prefer the configured physical ESP32 REAL
 // evidence so a newer simulated row cannot hide it.
 const realReadings=sorted.filter(r=>String(r?.source||"").toUpperCase()==="REAL"&&String(r?.device_id||"").toUpperCase()==="CRAI-ESP32-01");
 const current=realReadings[0]||sorted[0];
 const fresh=current&&ageMinutes(current.timestamp)<=15;
 const real=String(current?.source||"").toUpperCase()==="REAL";
 return <main className="content"><div className="page-head"><div><Eyebrow>SENSOR NETWORK · ENVIRONMENTAL EVIDENCE</Eyebrow><h1>Environmental evidence</h1><p>CRAI treats sensor readings as evidence with explicit source, freshness, and acquisition state.</p></div><div className="page-actions"><Button variant="secondary" onClick={simulate}><Icon name="spark"/> Simulate fresh reading</Button><Button onClick={acquire} loading={state==="loading"}><Icon name="wifi"/> {state==="loading"?"Waiting for ESP32…":"Acquire fresh reading"}</Button></div></div>
 <div className="sensor-grid"><Card className="sensor-primary"><div className="sensor-node-head"><div className="node-title"><div className="node-icon"><Icon name="chip" size={25}/></div><div><Eyebrow>CRAI-ESP32-01</Eyebrow><h2>Environmental sensor node</h2></div></div><StatusDot label={real?"REAL":"SIMULATED"} good={real}/></div><div className="sensor-values"><SensorValue label="Soil moisture" value={current?.soil_moisture} suffix="%"/><SensorValue label="Temperature" value={current?.temperature} suffix="°C"/><SensorValue label="Humidity" value={current?.humidity} suffix="%"/></div><div className="freshness-panel"><div><span>Evidence freshness</span><b>{current?`${ageMinutes(current.timestamp).toFixed(1)} min ago`:"No reading"}</b></div><div className="freshness-track"><i style={{width:`${fresh?Math.max(4,100-Math.min(100,ageMinutes(current.timestamp)/15*100)):4}%`}}/></div><div className="freshness-scale"><span>FRESH</span><span>15 MIN POLICY</span><span>STALE</span></div></div><div className="sensor-meta"><span>Source <b>{current?.source||"—"}</b></span><span>Zone <b>{current?.zone_id||"A1"}</b></span><span>Freshness <b>{current?freshness(current.timestamp):"—"}</b></span></div>{error&&<div className="error-banner"><b>Acquisition issue</b><span>{error}</span></div>}</Card>
 <Card className="network-card"><Eyebrow>NETWORK</Eyebrow><h2>Edge status</h2><StatusRow icon="chip" label="ESP32 node" value={online?"ONLINE":"OFFLINE"} good={online}/><StatusRow icon="wifi" label="Backend API" value={backend?"CONNECTED":"OFFLINE"} good={backend}/><StatusRow icon="leaf" label="Evidence store" value="ACTIVE" good/><StatusRow icon="refresh" label="Acquisition mode" value="REQUEST → READ"/><div className="network-note"><Icon name="shield" size={15}/><span>REAL readings must arrive through the ESP32 request/claim flow. Simulation is always labelled.</span></div></Card></div>
 <Card><div className="card-title-row"><div><Eyebrow>RECENT READINGS</Eyebrow><h2>Environmental stream</h2></div><span className="version-pill">{readings.length} READINGS</span></div><div className="reading-table"><div className="reading-row head"><span>TIME</span><span>SOURCE</span><span>ZONE</span><span>SOIL</span><span>TEMP</span><span>HUMIDITY</span></div>{sorted.slice(0,10).map((r,i)=><div className="reading-row" key={r.reading_id||i}><span>{fmtTime(r.timestamp)}</span><span className={String(r.source).toUpperCase()==="REAL"?"real-text":"sim-text"}>{r.source||"REAL"}</span><span>{r.zone_id||"A1"}</span><span>{r.soil_moisture==null?"—":`${Number(r.soil_moisture).toFixed(1)}%`}</span><span>{r.temperature==null?"—":`${Number(r.temperature).toFixed(1)}°C`}</span><span>{r.humidity==null?"—":`${Number(r.humidity).toFixed(1)}%`}</span></div>)}{!sorted.length&&<div className="table-empty">No sensor readings returned by the backend.</div>}</div></Card>
 </main>
}
function SensorValue({label,value,suffix}){return <div className="sensor-value"><span>{label}</span><strong>{value==null?"—":Number(value).toFixed(1)}<em>{suffix}</em></strong></div>}
function StatusRow({icon,label,value,good}){return <div className="status-row"><Icon name={icon} size={17}/><span>{label}</span><b className={good?"ok":""}>{value}</b></div>}
