import {useRef,useState,useEffect} from "react";
import {Send,Sparkles,ShieldCheck,Leaf,RefreshCw} from "lucide-react";
import {useFieldSelection} from "../app/FieldContext.jsx";
import {askCrai} from "../services/craiData.js";
const suggestions=["Why is my field at risk?","What should I do today?","What changed recently?","Why does CRAI need more evidence?"];
export default function AskCraiPage(){
 const {selected}=useFieldSelection(); const [messages,setMessages]=useState([]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const scroll=useRef(null);
 useEffect(()=>scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:"smooth"}),[messages,loading]);
 async function send(q){const text=(q??input).trim();if(!text||loading)return;setMessages(m=>[...m,{role:"user",text}]);setInput("");setLoading(true);try{const r=await askCrai(text,{farmId:selected.farmId,zoneId:selected.zoneId});setMessages(m=>[...m,{role:"ai",text:r?.answer||r?.message||"The assistant returned no explanation.",tag:r?.tag||"evidence"}])}catch{setMessages(m=>[...m,{role:"ai",text:"The CRAI explanation service is unavailable right now. I won't invent an answer or a risk score.",tag:"unknown"}])}finally{setLoading(false)}}
 return <div className="page ask-page"><div className="ask-hero"><div className="ask-hero-icon"><Sparkles size={24}/></div><div><div className="eyebrow">CRAI ASSISTANT</div><h1>Understand your field in simple language.</h1><p>Ask about evidence, changes, or what CRAI needs next. The assistant explains the intelligence layer — it does not calculate or override risk.</p></div></div>
 <div className="suggestions">{suggestions.map(q=><button key={q} onClick={()=>send(q)}><span>{q}</span><Send size={14}/></button>)}</div>
 <div className="chat-shell"><div className="chat-head"><div><b>Ask CRAI</b><span>{selected.fieldName} · {selected.zoneName}</span></div><span className="chat-safe"><ShieldCheck size={14}/> Evidence-grounded</span></div><div className="chat-scroll" ref={scroll}>{messages.length===0&&<div className="chat-empty"><div className="chat-empty-icon"><Leaf size={25}/></div><h3>What would you like to know?</h3><p>Try one of the questions above, or ask in your own words.</p></div>}{messages.map((m,i)=><div className={`chat-msg ${m.role}`} key={i}>{m.role==="ai"&&<div className="ai-avatar">CR</div>}<div><span className="msg-role">{m.role==="ai"?"CRAI":"You"}</span><p>{m.text}</p></div></div>)}{loading&&<div className="chat-msg ai"><div className="ai-avatar">CR</div><div><span className="msg-role">CRAI</span><p className="thinking"><RefreshCw size={14}/> Reviewing available evidence…</p></div></div>}</div><div className="chat-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask CRAI about your field…"/><button onClick={()=>send()} disabled={!input.trim()||loading} aria-label="Send"><Send size={17}/></button></div><div className="chat-note">CRAI explains available evidence. Deterministic risk remains outside the assistant.</div></div>
 </div>
}
